[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "masgent"
version = "0.1.0"
description = "Masgent: A Materials Simulation AI Agent Framework"
readme = "README.md"
authors = [{name = "Guangchen Liu", email = "gliu4@wpi.edu"}]
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "ase>=3.24.0",
    "numpy>=1.26.4",
    "pydantic_ai>=0.8.1",
    "pymatgen>=2024.10.3",
]

[project.optional-dependencies]
dev = ["pytest", "black", "ruff", "build", "twine"]
docs = ["mkdocs", "mkdocs-material"]

[project.urls]
Homepage = "https://github.com/aguang5241/masgent"
Issues = "https://github.com/aguang5241/masgent/issues"

[project.scripts]
masgent = "masgent.cli:main"