[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "masgent"
version = "0.2.4"
description = "Masgent: Materials Simulation Agent"
readme = "README.md"
authors = [{name = "Guangchen Liu", email = "gliu4@wpi.edu"}]
license = { file = "LICENSE" }
requires-python = ">=3.9, <3.13"
dependencies = [
    "ase>=3.24.0",
    "numpy>=1.26.4",
    "pydantic_ai>=0.8.1",
    "pymatgen>=2024.10.3",
    "mp-api>=0.45.13",
    "dotenv>=0.9.9",
    "colorama>=0.4.6",
    "tabulate>=0.9.0",
    "bullet>=2.2.0",
    "yaspin>=3.3.0",
]

[tool.setuptools.package-data]
"masgent" = ["ai_mode/system_prompt.txt"]

[project.optional-dependencies]
dev = ["pytest", "black", "ruff", "build", "twine"]
docs = ["mkdocs", "mkdocs-material"]

[project.urls]
Homepage = "https://github.com/aguang5241/masgent"
Issues = "https://github.com/aguang5241/masgent/issues"

[project.scripts]
masgent = "masgent.cli:main"